import TextBaseScene from '../TextBaseScene';

export default class Map006 extends TextBaseScene {
    constructor() {
        super({
            key: 'Map006',
            title: 'Narrow Passage',
            levelData: `
                ................
                ................
                ................
                .......*........
                .......-----....
                ......-.........
                ......-.........
                ......-.........
                ......-.........
                W.....--........
                ................
                ................
                ----------------
            `
        });
    }
}
