import TextBaseScene from '../TextBaseScene';

export default class Map005 extends TextBaseScene {
    constructor() {
        super({
            key: 'Map005',
            title: 'The Wall',
            levelData: `
                ................
                ................
                ................
                ..............*.
                .............---
                ................
                .......---......
                W...............
                ..---...........
                ................
                ----------------
            `
        });
    }
}
