import TextBaseScene from '../TextBaseScene';

export default class Map008 extends TextBaseScene {
    constructor() {
        super({
            key: 'Map008',
            title: 'The Spiral',
            levelData: `
                ...........
                ...........
                ...........
                ...........
                .....*.....
                .....------
                .....-.....
                .....-.....
                .....-.....
                .....---...
                ...........
                ....----...
                ...........
                W.------...
                ...........
                ...........
                -----------
            `
        });
    }
}
