import TextBaseScene from '../TextBaseScene';

export default class Map007 extends TextBaseScene {
    constructor() {
        super({
            key: 'Map007',
            title: 'Precision Jumps',
            levelData: `
                ................
                ................
                ................
                .............**.
                .............---
                ................
                ................
                .......---.....
                ................
                ................
                W.--............
                ................
                ................
                ----------------
            `
        });
    }
}
